name: Database Backup

on:
  schedule:
    - cron: "0 3 * * *" # runs daily at 3AM UTC
  workflow_dispatch: # allows manual trigger
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/db-backup.yml'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Dump database
        run: pg_dump $DATABASE_URL > backup.sql

      - name: List files (debug)
        run: ls -la

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exact-timestamps
        env:
          AWS_S3_BUCKET: community-db-backups-evanmeli1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: .
