name: Database Backup

on:
  schedule:
    - cron: "0 3 * * *" # runs daily at 3AM UTC
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/db-backup.yml'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL 17 client
         run: |
              sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
              wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
               sudo apt-get update
               sudo apt-get install -y postgresql-client-17


      - name: Dump database
        run: pg_dump "${{ secrets.DATABASE_URL }}" > backup.sql

      - name: List files (debug)
        run: ls -la

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exact-timestamps
        env:
          AWS_S3_BUCKET: community-db-backups-evanmeli1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          SOURCE_DIR: .
