name: Deploy Community Resource Mapper

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Debug repo contents
      run: |
        echo "PWD:"
        pwd
        echo "Top-level files:"
        ls -lah
        echo "Looking for package.json:"
        find . -maxdepth 2 -name "package.json"

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
